name: cannum
description: O app de mensagens da CanDev.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.1
  cloud_firestore: ^1.0.3

  # Plugins
  image_picker: ^0.7.4
  animated_text_kit: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tox Typewriter
      fonts:
        - asset: assets/fonts/Tox_Typewriter.ttf